### ISSUE TITLE
Ranking as integer not float

### ISSUE THREAD

**Issue by maciekkoz98** [POP-grupa-K/appstore-service#17]
Ranking should be a float/double value.
Need to have sth like 6.9 (hihihi!)

**Comment by maciekkoz98** [comment]
Issue applies to rating and appstore model

**Comment by GrzesiuKo** [comment]
Hallo @maciekkoz98 ,
Im Datenmodel steht, das "ranking" Feld in der Datenbank, soll Integer sein.
Ist diese Issue auch in Dev/Ops Gruppe gemeldet?

**Comment by maciekkoz98** [comment]
natürlich, es ist gemeldet

**Comment by GrzesiuKo** [comment]
Gut, also ich krieg das hin.

**Comment by GrzesiuKo** [comment]
Zmienione. Potrzebne jeszcze testy, gdy te zmiany zajdą też na backendzie.

**Comment by GrzesiuKo** [comment]
Camel Case musi być zwracany.
@jeleniep @GrzesiuKo

**Comment by GrzesiuKo** [comment]
Done #32
